# Generated by Django 4.2.4 on 2023-08-18 19:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_publish_bb7600_idx",
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="publish"),
        ),
    ]
